$('.owl-carousel').owlCarousel({
    loop:true,
    margin:10,
    nav:false,
    responsive:{
        0:{
            items:2
        },
        900:{
            items:4
        },
        1200:{
            items:7
        }
    }
})